routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CountryController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\SubCategoryController;
use App\Http\Controllers\ItemController;
use App\Http\Controllers\StoreController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('countries.index');
});
//Route::get('countries','CountryController@index');
//Countries routes
Route::group(['prefix'=>'countries','as'=>'countries.','controller'=>CountryController::class], function(){
    Route::get('/', 'index')->name('index');
    Route::get('/create', 'create')->name('create');
    Route::get('/{country}', 'show')->name('show');
    Route::get('/edit/{country}', 'edit')->name('edit');
    Route::delete('/{country}', 'destroy')->name('delete');
    Route::put('/{country}', 'update')->name('update');
    Route::post('/', 'store')->name('store');

});

Route::group(['prefix'=>'categories','as'=>'categories.','controller'=>CategoryController::class], function(){
    Route::get('/', 'index')->name('index');
    Route::get('/create', 'create')->name('create');
    Route::get('/{id}', 'show')->name('show');
    Route::get('/edit/{category}', 'edit')->name('edit');
    Route::delete('/{category}', 'destroy')->name('delete');
    Route::put('/{category}', 'update')->name('update');
    Route::post('/', 'store')->name('store');

    Route::group(['prefix'=>'{categoryId}/sub-categories','as'=>'sub-categories.','controller'=>SubCategoryController::class], function(){
        Route::get('/', 'index')->name('index');
        Route::get('/create', 'create')->name('create');
        Route::get('/{subCategoryId}', 'show')->name('show');
        Route::delete('/{subCategoryId}', 'destroy')->name('delete');
        Route::put('/{subCategoryId}', 'update')->name('update');
        Route::post('/', 'store')->name('store');
    
    });

});

Route::group(['prefix'=>'items','as'=>'items.','controller'=>ItemController::class], function(){
    Route::get('/', 'index')->name('index');
    Route::get('/create', 'create')->name('create');
    Route::get('/{id}', 'show')->name('show');
    Route::delete('/{id}', 'destroy')->name('delete');
    Route::put('/{id}', 'update')->name('update');
    Route::post('/', 'store')->name('store');
    Route::get('/edit/{id}', 'edit')->name('edit');

});

Route::group(['prefix'=>'stores','as'=>'stores.','controller'=>StoreController::class], function(){
    Route::get('/', 'index')->name('index');
    Route::get('/create', 'create')->name('create');
    Route::get('/{id}', 'show')->name('show');
    Route::delete('/{id}', 'destroy')->name('delete');
    Route::put('/{id}', 'update')->name('update');
    Route::post('/', 'store')->name('store');
    Route::get('/edit/{id}', 'edit')->name('edit');

});



Route::get('/login', function () {
    return view('auth.login');
});

app/Models/Category.php
<?php

namespace App\Models;

use App\Traits\hasTranslations;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;

class Category extends Model
{
    use hasTranslations;

    protected $fillable=[
        'title_author_id',
        'image_url'
    ];

    protected $hidden=[
        'title_author_id',
        'translations'
    ];

    protected $with=[
        'author',
        'translations'
    ];

    protected $appends=[
        'title',
    ];

    public function author()
    {
        return $this->hasOne(User::class,'id','title_author_id');
    }

    public function getTitleAttribute()
    {
        if(request()->has('language')){
            $language=$this->translations->where(
            'language_id',
            get_language_id_by_iso(request('language')??1
            ))->first();

            return  $language
                    ? $language->title:'';
        }     

        
    }

}

app/Http/Controllers/Api/CategoryController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Repositories\CategoriesRepository;
use App\Http\Requests\CategoryStoreRequest;

class CategoryController extends ApiBaseController
{
    protected $repo;

    public function __construct(CategoriesRepository $categoriesRepo)
    {
        $this->repo=$categoriesRepo;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return response(
            $this->repo->fetchAll(false,true)
                ->toJson(JSON_PRETTY_PRINT)
        );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryStoreRequest $request)
    {
        $image_path='';

        if($request->has('image')){
            $imageName = time().'.'.$request->image->extension();  
     
            $image_path= $request->image->move(storage_path('images/category/images'), $imageName);
        }

        $this->repo->save($request->all() + ['image_url' => $image_path]);

       return  response()->json([
           'success'=>'Category has been created.'
       ]);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return response()->json([
            $this->repo->fetchOne('id',$id)
        ]);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Repositories\CategoriesRepository;
use Yajra\DataTables\Facades\DataTables;
use Illuminate\Support\Str;

class CategoryController extends Controller
{

    protected $repo;

    public function __construct(CategoriesRepository $categoriesRepo)
    {
        $this->repo=$categoriesRepo;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
        $data = $this->repo->fetchAll();

        $request=request();
        if ($request->ajax()) {
            return DataTables::of($data)
                ->editColumn('title_en', function($data)
                {
                   return $data->translations->where('language_id',1)->first()->title;
                })
                ->editColumn('title_ar', function($data)
                {
                   return $data->translations->where('language_id',2)->first()->title;
                })
                ->addIndexColumn()
                ->addColumn('action', 'categories.action')
                ->rawColumns(['action'])
                ->addIndexColumn()
                ->make(true);
        }

        $page_title = 'Categories';
        $page_description = 'This page is to show all the records in country table';

        return view('categories.index', compact('page_title', 'page_description','data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $page_title = 'Categories';
        $page_description = 'This page is to create new category';

        return view('categories.create', compact('page_title', 'page_description'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
        $request->validate([
            'title_en'=>'required_without:title_ar',
            'title_ar'=>'required_without:title_en',
            'image'=>'required|image|mimes:png,jpeg,gif'
        ]);

        $this->repo->save($request->all()+['title_author_id'=>1]);

        return back()->with(['success'=>'New Category has been added']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $entity=$this->repo->fetchOne('id',$id);
        if(!$entity)
            return redirect('/')->with('error','not found');
            
        $className=class_basename($entity);
        $page_title = 'Show '.$className;
        $page_description = "This page is to show $className details";
        
        return view(Str::plural($className).'.show',compact('entity','className', 'page_title', 'page_description'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $entity=$this->repo->fetchOne('id',$id);
        if(!$entity)
            return redirect('/')->with('error','not found');
            
        $className=class_basename($entity);
        $page_title = 'Show '.$className;
        $page_description = "This page is to edit $className details";
        
        return view(Str::plural($className).'.show',compact('entity','className', 'page_title', 'page_description'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {
        $this->repo->update($id,$request);

        return back()->with('success','Category has been updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->repo->delete($id);

        return response()->json([
            'message'=>'success'
        ]);
    }
}

resources/views/categories/action.blade.php
<a href="{{ route('categories.show',$id) }}" class="btn btn-sm btn-clean btn-icon" title="View details">
    <i class="la la-eye"></i>
</a>
<a href="{{ route('categories.edit',$id) }}" class="btn btn-sm btn-clean btn-icon" title="Edit details">
    <i class="la la-edit"></i>
</a>
<a href="javascript:void(0)" data-id="{{ $id }}" class="delete btn btn-sm btn-clean btn-icon" title="Delete">
    <i class="la la-trash"></i>
</a>

resources/views/categories/create.blade.php
{{-- Extends layout --}}
@extends('layout.default')

{{-- Content --}}
@section('content')

<div class="card card-custom example example-compact">
    <div class="card-header">
        <h3 class="card-title">
            Add New Category
        </h3>
        <div class="card-toolbar">
            <div class="example-tools justify-content-center">
            <a href="{{ route('categories.index') }}" class="btn btn-secondary">Go Back</a>
            </div>
        </div>
    </div>
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <!--begin::Form-->
    <form action="{{ route('categories.store') }}" method="POST" enctype="multipart/form-data" id="category_create_form">
        @csrf
        <div class="card-body">
            <div class="form-group row">
                <div class="col-lg-4">
                    <label>Title English<span class="text-danger">*</span></label>
                    <input type="text" name="title_en"  class="form-control" placeholder="Enter English Name"/>
                    <span class="form-text text-muted">Please enter English Name, Max 50 character allowed</span>
                </div>
                <div class="col-lg-4">
                    <label>Title Arabic</label>
                    <input type="text" name="title_ar" class="form-control" placeholder="Enter Arabic Name"/>
                    <span class="form-text text-muted">Please enter Arabic Name, Max 50 character allowed</span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-lg-4">
                    <label>Image<span class="text-danger">*</span></label>
                    <div class="image-input image-input-empty image-input-outline" id="kt_image_5" style="background-image: url(/media/users/blank.png)">
                        <input type="file" name="image" accept=".png, .jpg, .jpeg"/>
                        </label>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <div class="row">
                <div class="col-lg-4"></div>
                <div class="col-lg-8">
                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    <button type="reset" class="btn btn-secondary">Cancel</button>
                </div>
            </div>
        </div>
    </form>
    <!--end::Form-->
</div>

@endsection

{{-- Scripts Section --}}
@section('scripts')
<script>
    @if(session()->has('success'))
    swal.fire({
            title: "{{ session()->get('success') }}",
            type: 'success',
            buttonsStyling: false,
            confirmButtonText: 'Awesome!',
            confirmButtonClass: 'btn btn-primary font-weight-bold'
        });
   @endif

    var avatar5 = new KTImageInput('kt_image_5');

    avatar5.on('cancel', function(imageInput) {
        swal.fire({
            title: 'Image successfully changed !',
            type: 'success',
            buttonsStyling: false,
            confirmButtonText: 'Awesome!',
            confirmButtonClass: 'btn btn-primary font-weight-bold'
        });
    });

    avatar5.on('change', function(imageInput) {
        swal.fire({
            title: 'Image successfully changed !',
            type: 'success',
            buttonsStyling: false,
            confirmButtonText: 'Awesome!',
            confirmButtonClass: 'btn btn-primary font-weight-bold'
        });
    });

    avatar5.on('remove', function(imageInput) {
        swal.fire({
            title: 'Image successfully removed !',
            type: 'error',
            buttonsStyling: false,
            confirmButtonText: 'Got it!',
            confirmButtonClass: 'btn btn-primary font-weight-bold'
        });
    });

</script>
@endsection

resources/views/categories/edit.blade.php
{{-- Extends layout --}}
@extends('layout.default')


{{-- Content --}}
@section('content')

<div class="card card-custom example example-compact">
    <div class="card-header">
        <h3 class="card-title">
            Edit Country
        </h3>
        <div class="card-toolbar">
            <div class="example-tools justify-content-center">
            <a href="{{ route('countries.index') }}" class="btn btn-secondary">Go Back</a>
            </div>
        </div>
    </div>
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <!--begin::Form-->
    <form action="{{ route('countries.update',$country->id) }}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <div class="card-body">
            <div class="form-group row">
                <div class="col-lg-4">
                    <label>ID<span class="text-danger">*</span></label>
                    <input type="text" name="id" value="{{ $country->id }}" disabled class="form-control" placeholder="Enter ISO"/>
                    <span class="form-text text-muted">Please enter ISO, Max 2 character allowed</span>
                </div>
                <div class="col-lg-4">
                    <label>Name English<span class="text-danger">*</span></label>
                    <input type="text" name="name" value="{{ $country->name_en }}" required class="form-control" placeholder="Enter Name"/>
                    <span class="form-text text-muted">Please enter Name, Max 50 character allowed</span>
                </div>
                <div class="col-lg-4">
                    <label>Name Arabic<span class="text-danger">*</span></label>
                    <input type="text" name="name_local" value="{{ $country->name_ar }}" class="form-control" placeholder="Enter Local Name"/>
                    <span class="form-text text-muted">Please enter Local Name, Max 50 character allowed</span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-lg-4">
                    <label>Image<span class="text-danger">*</span></label>
                    <div class="image-input image-input-outline" id="kt_image_4" >
                        <div class="image-input-wrapper" style="background-image: url({{$country->flag_url}})"></div>
                        <label class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow" data-action="change" data-toggle="tooltip" title="" data-original-title="Change avatar">
                        <i class="fa fa-pen icon-sm text-muted"></i>
                        <input type="file" name="image" accept=".png, .jpg, .jpeg"/>
                        <input type="hidden" name="profile_avatar_remove"/>
                        </label>

                        <span class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow" data-action="cancel" data-toggle="tooltip" title="Cancel avatar">
                        <i class="ki ki-bold-close icon-xs text-muted"></i>
                        </span>

                        <span class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow" data-action="remove" data-toggle="tooltip" title="Remove avatar">
                        <i class="ki ki-bold-close icon-xs text-muted"></i>
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <div class="row">
                <div class="col-lg-4"></div>
                <div class="col-lg-8">
                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    <button type="reset" class="btn btn-secondary">Cancel</button>
                </div>
            </div>
        </div>
    </form>
    <!--end::Form-->
</div>

@endsection

{{-- Scripts Section --}}
@section('scripts')
<script>
    var avatar4 = new KTImageInput('kt_image_4');

    avatar4.on('cancel', function(imageInput) {
        swal.fire({
            title: 'Image successfully canceled !',
            type: 'success',
            buttonsStyling: false,
            confirmButtonText: 'Awesome!',
            confirmButtonClass: 'btn btn-primary font-weight-bold'
        });
    });

    avatar4.on('change', function(imageInput) {
        swal.fire({
            title: 'Image successfully changed !',
            type: 'success',
            buttonsStyling: false,
            confirmButtonText: 'Awesome!',
            confirmButtonClass: 'btn btn-primary font-weight-bold'
        });
    });

    avatar4.on('remove', function(imageInput) {
        swal.fire({
            title: 'Image successfully removed !',
            type: 'error',
            buttonsStyling: false,
            confirmButtonText: 'Got it!',
            confirmButtonClass: 'btn btn-primary font-weight-bold'
        });
    });
</script>
@endsection

resources/views/categories/index.blade.php
{{-- Extends layout --}}
@extends('layout.default')

{{-- Content --}}
@section('content')

    <div class="card card-custom">
        <div class="card-header flex-wrap border-0 pt-6 pb-0">
            <div class="card-title">
                <h3 class="card-label">Categories
                    <div class="text-muted pt-2 font-size-sm">All Categories Datatable</div>
                </h3>
            </div>
            <div class="card-toolbar">
                <!--begin::Button-->
                <a href="{{route('categories.create')}}" class="btn btn-primary font-weight-bolder">
                <i class="la la-plus"></i>New Record</a>
                <!--end::Button-->
            </div>
        </div>

        <div class="card-body">
            @if ($message = Session::get('success'))
            <div id="alert" class="alert alert-custom alert-notice alert-light-success fade show" role="alert">
                <!-- <div class="alert-icon"><i class="flaticon-warning"></i></div> -->
                <div class="alert-text">{{ $message }}</div>
                <div class="alert-close">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true"><i class="ki ki-close"></i></span>
                    </button>
                </div>
            </div>
            @endif
            <table class="table table-bordered table-hover main_datatable" id="kt_datatable">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Title English</th>
                    <th>Title Arab</th>
                    <th>Image</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                </tbody>

            </table>

        </div>

    </div>

@endsection

{{-- Styles Section --}}
@section('styles')
    <link href="{{ asset('plugins/custom/datatables/datatables.bundle.css') }}" rel="stylesheet" type="text/css"/>
@endsection


{{-- Scripts Section --}}
@section('scripts')
    {{-- vendors --}}
    <script src="{{ asset('plugins/custom/datatables/datatables.bundle.js') }}" type="text/javascript"></script>

    {{-- page scripts --}}
    <script type="text/javascript">
        $(function () {
            var table = $('.main_datatable').DataTable({
                processing: true,
                serverSide: true,
                ajax: "#",
                columns: [
                    {data: 'id', name: 'id'},
                    {data: 'title_en', name: 'title_en'},
                    {data: 'title_ar', name: 'title_ar'},
                    {data: 'image_url', name: 'image',"render": function (data, type, full, meta) {
                        return "<img src=\"" + data + "\" height=\"80px\"/>"}
                    },
                    {data: 'action', name: 'action', orderable: false, searchable: false},
                ]
            });
        });

        $('body').on('click', '.delete', function () {
            var id = $(this).data('id');
            Swal.fire({
                title: "Are you sure?",
                text: "You won't be able to revert this!",
                icon: "warning",
                showCancelButton: true,
                confirmButtonText: "Yes, delete it!"
            }).then(function(result) {
                if (result.value) {

                    // ajax
                    $.ajax({
                        type:"DELETE",
                        url: "/categories/"+id,
                        data:{
                            '_token': '{{ csrf_token() }}',
                        },
                        dataType: 'json',
                        success: function(res){
                            $('.main_datatable').DataTable().ajax.reload();
                        }
                    });
                    Swal.fire(
                        "Deleted!",
                        "Record has been deleted.",
                        "success"
                    );
                }
            });
        });
    </script>
    @if ($message = Session::get('success'))
    <script>
        $('#alert').show();
            setTimeout(function() {
                $('#alert').hide();
        }, 5000);
    </script>
    @endif
@endsection

resources/views/categories/show.blade.php
{{-- Extends layout --}}
@extends('layout.default')

{{-- Content --}}
@section('content')

<div class="card card-custom example example-compact">
    <div class="card-header">
        <h3 class="card-title">
            View {{Str::plural($className)}}  # &nbsp {{ $entity->id }}
        </h3>
        <div class="card-toolbar">
            <div class="example-tools justify-content-center">
            <a href="{{ route('categories.index') }}" class="btn btn-secondary">Go Back</a>
            <a href="{{ route('categories.sub-categories.index',$entity->id) }}" class="ml-2 btn btn-primary">Go to Sub Categories</a>
            </div>
        </div>
    </div>
    <form action="{{ route('categories.update',$entity->id) }}" method="POST" enctype="multipart/form-data">
        {{ method_field('PUT') }}
        {{csrf_field()}}
         <div class="card-body">
            <div class="form-group row">
                <div class="col-lg-6">
                    <label>Title English<span class="text-danger">*</span></label>
                    <input type="text" name="title_en" value="{{ $entity->translations()->where('language_id',get_language_id_by_iso('en'))->first()->title??null }}" disabled class="form-control" placeholder="Enter Name"/>
                    <span class="form-text text-muted">Please enter English Title, Max 50 character allowed</span>
                </div>
                <div class="col-lg-6">
                    <label>Title Arabic</label>
                    <input type="text" name="title_ar" value="{{ $entity->translations()->where('language_id',get_language_id_by_iso('ar'))->first()->title??null }}" disabled  class="form-control" placeholder="Enter Local Name"/>
                    <span class="form-text text-muted">Please enter Arabic Title, Max 50 character allowed</span>
                </div>
            <div class="form-group row">
                <div class="col-lg-6">
                    <label>Image<span class="text-danger">*</span></label>
                    <div class="image-input image-input-outline" id="kt_image_4" >
                        <div class="image-input-wrapper" style="background-image: url({{$entity->image_url}})"></div>
                        <label class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow" data-action="change" data-toggle="tooltip" title="" data-original-title="Change avatar" name="change-image">
                        <i class="fa fa-pen icon-sm text-muted"></i>
                        <input type="file" name="image" accept=".png, .jpg, .jpeg"/>
                        <input type="hidden" name="profile_avatar_remove"/>
                        </label>

                        <span class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow" data-action="cancel" data-toggle="tooltip" title="Cancel avatar">
                        <i class="ki ki-bold-close icon-xs text-muted"></i>
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <div class="row">
                <div class="col-lg-4"></div>
                <div class="col-lg-8">
                    <a href="#" id="category-edit-enable"  class="btn btn-primary mr-2">Edit</a>
                    <button href="#q" id="category-submit" type="submit"  class="btn btn-primary mr-2">Save</button>
                    <a href="#" id="category-cancel"  class="btn btn-primary mr-2">cancel</a>
                </div>
            </div>
        </div>
</form>
</div>

@endsection

{{-- Scripts Section --}}
@section('scripts')
<script>
    var avatar4 = new KTImageInput('kt_image_4');

    $('#change-image').hide();
    $('#category-submit').hide();

    $('#category-edit-enable').click(function(e){
        e.preventDefault();
        $('[name=title_en],[name=title_ar]').removeAttr("disabled");
        $('#change-image').show();
        $('#category-submit').fadeIn();
    });


</script>
@endsection