routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CountryController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\SubCategoryController;
use App\Http\Controllers\ItemController;
use App\Http\Controllers\StoreController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('countries.index');
});
//Route::get('countries','CountryController@index');
//Countries routes
Route::group(['prefix'=>'countries','as'=>'countries.','controller'=>CountryController::class], function(){
    Route::get('/', 'index')->name('index');
    Route::get('/create', 'create')->name('create');
    Route::get('/{country}', 'show')->name('show');
    Route::get('/edit/{country}', 'edit')->name('edit');
    Route::delete('/{country}', 'destroy')->name('delete');
    Route::put('/{country}', 'update')->name('update');
    Route::post('/', 'store')->name('store');

});

Route::group(['prefix'=>'categories','as'=>'categories.','controller'=>CategoryController::class], function(){
    Route::get('/', 'index')->name('index');
    Route::get('/create', 'create')->name('create');
    Route::get('/{id}', 'show')->name('show');
    Route::get('/edit/{category}', 'edit')->name('edit');
    Route::delete('/{category}', 'destroy')->name('delete');
    Route::put('/{category}', 'update')->name('update');
    Route::post('/', 'store')->name('store');

    Route::group(['prefix'=>'{categoryId}/sub-categories','as'=>'sub-categories.','controller'=>SubCategoryController::class], function(){
        Route::get('/', 'index')->name('index');
        Route::get('/create', 'create')->name('create');
        Route::get('/{subCategoryId}', 'show')->name('show');
        Route::delete('/{subCategoryId}', 'destroy')->name('delete');
        Route::put('/{subCategoryId}', 'update')->name('update');
        Route::post('/', 'store')->name('store');
    
    });

});

Route::group(['prefix'=>'items','as'=>'items.','controller'=>ItemController::class], function(){
    Route::get('/', 'index')->name('index');
    Route::get('/create', 'create')->name('create');
    Route::get('/{id}', 'show')->name('show');
    Route::delete('/{id}', 'destroy')->name('delete');
    Route::put('/{id}', 'update')->name('update');
    Route::post('/', 'store')->name('store');
    Route::get('/edit/{id}', 'edit')->name('edit');

});

Route::group(['prefix'=>'stores','as'=>'stores.','controller'=>StoreController::class], function(){
    Route::get('/', 'index')->name('index');
    Route::get('/create', 'create')->name('create');
    Route::get('/{id}', 'show')->name('show');
    Route::delete('/{id}', 'destroy')->name('delete');
    Route::put('/{id}', 'update')->name('update');
    Route::post('/', 'store')->name('store');
    Route::get('/edit/{id}', 'edit')->name('edit');

});



Route::get('/login', function () {
    return view('auth.login');
});

app/Models/Item.php
<?php

namespace App\Models;

use App\Traits\hasTranslations;
use Illuminate\Database\Eloquent\Model;
use App\Models\Category;
use App\Models\SubCategory;
use App\Models\User;
use App\Models\ItemImage;
use App\Models\Store;

class Item extends Model
{
    use hasTranslations;

    protected $fillable=[
        'category_id',
        'sub_category_id',
        'title_author_id',
        'des_author_id',
        'price',
        'new_price',
        'arrival_range',
        'in_stock'
    ];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function subCategory()
    {
        return $this->belongsTo(SubCategory::class);
    }

    public function titleAuthor()
    {
        return $this->belongsTo(User::class,'title_author_id');
    }

    public function descriptionAuthor()
    {
        return $this->belongsTo(User::class,'des_author_id');
    }

    public function images()
    {
        return $this->hasMany(ItemImage::class);
    }

    public function stores()
    {
        return $this->belongsToMany(Store::class);
    }
}

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Repositories\ItemsRepository;
use Yajra\DataTables\Facades\DataTables;
use App\Traits\HasLanguages;
use Illuminate\Support\Str;

class ItemController extends Controller
{
    use HasLanguages;

    protected $repo;

    public function __construct(ItemsRepository $itemsRepo)
    {
        $this->repo=$itemsRepo;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {       
        session(['language' => 2]);

        $filter=$this->repo->getFilter();

        if($priceFrom=request('price_from')){
            $filter->where('price','>',$priceFrom);
        }
        if($priceTo=request('price_to')){
            $filter->where('price','<',$priceTo);
        }
        if($subCategoryId=request('sub_category')){
            $filter->where('sub_category_id',$subCategoryId);
        }
        if($city=request('city')){
            $filter->whereHas('stores',function($stores)use($city){
                return $stores->whereHas('cities',function($cities)use($city){
                    return $cities->where('city_id',$city);
                });
            });
        }
        if($area=request('area')){
            $filter->whereHas('stores',function($stores)use($area){
                return $stores->whereHas('areas',function($cities)use($area){
                    return $cities->where('area_id',$area);
                });
            });
        }
        if($stock=request('stock')){
            $filter->where('in_stock','>=',$stock);
        }

        
        $data = $this->repo->applyFilter($filter);

        $request=request();
        if ($request->ajax()) {
            return DataTables::of($data)
                ->editColumn('title', function($data)
                {
                   return $data->translations
                   ->where('language_id',session('language'))
                   ->first()
                   ->title;
                })
                ->editColumn('description', function($data)
                {
                   return $data->translations
                   ->where('language_id',session('language'))
                   ->first()
                   ->description;
                })
                ->editColumn('category', function($data)
                {
                   return $data->category
                   ->translations
                   ->where('language_id',session('language')
                   )->first()
                   ->title;
                })
                ->editColumn('sub_category', function($data)
                {
                   return $data->subCategory
                   ->translations
                   ->where('language_id',session('language'))
                   ->first()
                   ->title;
                })
                ->editColumn('title_author', function($data)
                {
                   return $data->titleAuthor->name;
                })
                ->editColumn('description_author', function($data)
                {
                   return $data->descriptionAuthor->name;
                })
                ->editColumn('areas', function($data)
                {
                    $storesIds=$data->stores->pluck('id');
                    $areaIds=\DB::table('area_store')->whereIn('store_id',$storesIds)->pluck('area_id');
                    $areaNames=\DB::table('area_translations')->whereIn('area_id',$areaIds)->where('language_id',1)->pluck('name');
                    
                    if(!empty($areaNames)){
                        return implode(",",$areaNames->toArray());
                    }
                    return '';
                })
                ->editColumn('cities', function($data)
                {
                    $storesIds=$data->stores->pluck('id');
                    $cityIds=\DB::table('city_store')->whereIn('store_id',$storesIds)->pluck('city_id');
                    $cityNames=\DB::table('city_translations')->whereIn('city_id',$cityIds)->where('language_id',1)->pluck('name');
                    
                    if(!empty($cityNames)){
                        return implode(",",$cityNames->toArray());
                    }
                    return '';
                })
                ->addIndexColumn()
                ->addColumn('action', 'items.action')
                ->rawColumns(['action'])
                ->addIndexColumn()
                ->make(true);
        }

        $page_title = 'Items';
        $page_description = 'This page is to show all the records in items table';

        return view('items.index', compact('page_title', 'page_description','data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $page_title = 'Items';
        $page_description = 'This page is to create new item';

        return view('items.create', compact('page_title', 'page_description'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {      
                
        $request->validate([
            'title_en'=>'required',
            'description_en'=>'required',
            'title_ar'=>'required',
            'description_ar'=>'required',
            'category_id'=>'required|exists:categories,id',
            'sub_category_id'=>'required|exists:sub_categories,id',
            'title_author_id'=>'required|exists:users,id',
            'des_author_id'=>'required|exists:users,id',
            'price'=>'required',
            'arrival_range'=>'required',
            'in_stock'=>'required'
        ]);      

        $this->repo->save($request);

        return back()->with(['success'=>'New Category has been added']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {session(['language' => '2']);
        $entity=$this->repo->fetchOne('id',$id);
        if(!$entity)
            return redirect('/')->with('error','not found');
            
        $className=class_basename($entity);
        $page_title = 'Show '.$className;
        $page_description = "This page is to show $className details";
        
        return view(Str::plural($className).'.show',compact('entity','className', 'page_title', 'page_description'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $entity=$this->repo->fetchOne('id',$id);
        if(!$entity)
            return redirect('/')->with('error','not found');
            
        $className=class_basename($entity);
        $page_title = 'Show '.$className;
        $page_description = "This page is to edit $className details";
        
        return view(Str::plural($className).'.show',compact('entity','className', 'page_title', 'page_description'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {
        $this->repo->update($id,$request);

        return back()->with('success','Category has been updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->repo->delete($id);

        return response()->json([
            'message'=>'success'
        ]);
    }
}

resources/views/items/action.blade.php
<a href="{{ route('items.show',$id) }}" class="btn btn-sm btn-clean btn-icon" title="View details">
    <i class="la la-eye"></i>
</a>
<a href="{{ route('items.edit',$id) }}" class="btn btn-sm btn-clean btn-icon" title="Edit details">
    <i class="la la-edit"></i>
</a>
<a href="javascript:void(0)" data-id="{{ $id }}" class="delete btn btn-sm btn-clean btn-icon" title="Delete">
    <i class="la la-trash"></i>
</a>

resources/views/items/create.blade.php
{{-- Extends layout --}}
@extends('layout.default')

{{-- Content --}}
@section('content')

<div class="card card-custom example example-compact">
    <div class="card-header">
        <h3 class="card-title">
            Create new Item
        </h3>
        <div class="card-toolbar">
            <div class="example-tools justify-content-center">
                <a href="{{ route('categories.index') }}" class="btn btn-secondary">Go Back</a>
            </div>
        </div>
    </div>
    @if ($errors->any()){{$errors}}
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form action="{{ route('items.store') }}" method="POST" enctype="multipart/form-data">
        
        {{csrf_field()}}
         <div class="card-body">
            <div class="form-group row">
                <div class="col-lg-6">
                    <label>Title English<span class="text-danger">*</span></label>
                    <input type="text" name="title_en" value="{{old('title')}}"  class="form-control" placeholder="Enter item name"/>
                </div>
                <div class="col-lg-6">
                    <label>Title Arabic<span class="text-danger">*</span></label>
                    <input type="text" name="title_ar" value="{{old('title')}}"  class="form-control" placeholder="أدخل عنوان البند"/>
                </div>
            </div>
            <div class="form-group row">                
                <div class="col-lg-6">
                    <label>Description English</label>
                    <textarea name="description_en" id="" cols="30" rows="10" class="form-control">                        
                    </textarea>
                </div>
                <div class="col-lg-6">
                    <label>Description Arabic</label>
                    <textarea name="description_ar" id="" cols="30" rows="10" class="form-control">                        
                    </textarea>
                </div>
            </div>
            <div class="form-group row">
                    <div class="col-lg-6">
                        <label>Category</label>
                        <select class="form-select form-control" name="category_id" data-control="select2" id="category-select" data-placeholder="Select an option">
                            <option>No categories</option>
                        </select>
                        <span class="form-text text-muted">Category of the item</span>
                    </div>
                    <div class="col-lg-6">
                        <label>Sub Category</label>
                        <select class="form-select form-control" name="sub_category_id" data-control="select2"  id="sub-category-select" data-placeholder="Select an option">
                            <option>No categories</option>
                        </select>
                        <span class="form-text text-muted">Sub category of the item</span>
                    </div>
            </div>
            <div class="form-group row">
                <div class="col-lg-6">
                    <label>Title Author<span class="text-danger">*</span></label>
                    <input type="text" name=""  value="to do"  class="form-control" placeholder="Enter Name" disabled />
                    <input type="hidden" name="title_author_id"  value="1"  class="form-control" placeholder="Enter Name" />
                </div>
                <div class="col-lg-6">
                    <label>Description Author<span class="text-danger">*</span></label>
                    <input type="text" name="" value="to do"  class="form-control" placeholder="Enter Name" disabled/>
                    <input type="hidden" name="des_author_id"  value="1"  class="form-control" placeholder="Enter Name" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-lg-6">
                    <label>Price<span class="text-danger">*</span></label>
                    <input type="text" name="price" value=""  class="form-control" placeholder="Enter Name"/>
                </div>
                <div class="col-lg-6">
                    <label>New Price<span class="text-danger">*</span></label>
                    <input type="text" name="new_price" value=""  class="form-control" placeholder="Enter Name"/>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-lg-6">
                    <label>Arrival Range<span class="text-danger">*</span></label>
                    <input type="text" name="arrival_range" value=""  class="form-control" placeholder="Enter Name"/>
                </div>
                <div class="col-lg-6">
                    <label>Stock<span class="text-danger">*</span></label>
                    <input type="number" name="in_stock" value=""  class="form-control" placeholder="Enter Name"/>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-lg-12">
                    <label>Stores<span class="text-danger">*</span></label><br>
                    <select name="stores[]" id="stores_select" class="form-control mt-multiselect"  multiple="multiple">

                    </select>
                </div>
            </div>                
            <div class="form-group row">
                <div class="col-lg-6">
                    <label>Image<span class="text-danger">*</span></label>
                    <div class="user-image mb-3 text-center">
                <div class="imgPreview"> </div>
            </div>            
            <div class="custom-file">
                <input type="file" name="imageFile[]" class="custom-file-input" id="images" multiple="multiple">
                <label class="custom-file-label" for="images">Choose image</label>
            </div>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <div class="row">
                <div class="col-lg-6"></div>
                <div class="col-lg-8">
                    <button href="#q"  type="submit"  class="btn btn-primary mr-2">Save</button>
                    <a href="#" id="category-cancel"  class="btn btn-primary mr-2">cancel</a>
                </div>
            </div>
        </div>
</form>
</div>

@endsection

@section('styles')
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<link rel="stylesheet" href="/css/plugins/bootstrap-multiselect.css" type="text/css"/>
@endsection

{{-- Scripts Section --}}
@section('scripts')
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script type="text/javascript" src="/js/plugins/bootstrap-multiselect.js"></script>
<script>
    var avatar4 = new KTImageInput('kt_image_4');

        var multiImgPreview = function(input, imgPreviewPlaceholder) {
            if (input.files) {
                var filesAmount = input.files.length;
                for (i = 0; i < filesAmount; i++) {
                    var reader = new FileReader();
                    reader.onload = function(event) {
                        $($.parseHTML('<img>'))
                            .attr('src', event.target.result)
                            .attr('width', '100px')
                            .attr('class', 'image-title')
                            .appendTo(imgPreviewPlaceholder);
                    }
                    reader.readAsDataURL(input.files[i]);
                }
            }
        };
        $('#images').on('change', function() {
            multiImgPreview(this, 'div.imgPreview');
        });

        $.ajax({
            type: "GET",
            url: '/api/categories?language=ar',
            beforeSend: function (xhr) {
                xhr.setRequestHeader('Authorization', 'Bearer 2|eCpELKhk7BPlE1avdZwQzbeB9djAxaicpZa5k5Hp');
            },
            success: function(data){
                $('#category-select').empty()
                $.each(JSON.parse(data), function(key,val) {
                    $('#category-select').append($("<option></option>")
                                            .attr("value", val.id)
                                            .text(val.title)); 
                });
                
               
                
            }
        });

        $.ajax({
            type: "GET",
            url: '/api/sub-categories?language=ar',
            beforeSend: function (xhr) {
                xhr.setRequestHeader('Authorization', 'Bearer 2|eCpELKhk7BPlE1avdZwQzbeB9djAxaicpZa5k5Hp');
            },
            success: function(data){
                $('#sub-category-select').empty()
                $.each(JSON.parse(data), function(key,val) {
                    $('#sub-category-select').append($("<option></option>")
                                            .attr("value", val.id)
                                            .text(val.title)); 
                 } );
                
               
                
            }
        });

        $('#stores_select').multiselect({
            enableFiltering: true,
            enableCaseInsensitiveFiltering: true
        });

        $.ajax({
            type: "GET",
            url: '/api/stores?language=en',
            beforeSend: function (xhr) {
                xhr.setRequestHeader('Authorization', 'Bearer 2|eCpELKhk7BPlE1avdZwQzbeB9djAxaicpZa5k5Hp');
            },
            success: function(data){
                $('#stores_select').empty()
                $.each(JSON.parse(data), function(key,val) {
                    $('#stores_select').append($("<option></option>")
                                            .attr("value", val.id)
                                            .text(val.title)); 
                 });
                $("#stores_select").multiselect('rebuild');                   
            }
        });

        $('#category-select').on('change', function() {
            $.ajax({
                type: "GET",
                url: '/api/categories/'+this.value+'/sub-categories?language=ar',
                beforeSend: function (xhr) {
                    xhr.setRequestHeader('Authorization', 'Bearer 2|eCpELKhk7BPlE1avdZwQzbeB9djAxaicpZa5k5Hp');
                },
                success: function(data){
                    $('#sub-category-select').empty()
                    $.each(JSON.parse(data), function(key,val) {
                        $('#sub-category-select').append($("<option></option>")
                                                .attr("value", val.id)
                                                .text(val.title)); 
                    });
                    
                
                    
                }
            });
        });

</script>
@endsection

resources/views/items/edit.blade.php
{{-- Extends layout --}}
@extends('layout.default')


{{-- Content --}}
@section('content')

<div class="card card-custom example example-compact">
    <div class="card-header">
        <h3 class="card-title">
            Edit Country
        </h3>
        <div class="card-toolbar">
            <div class="example-tools justify-content-center">
            <a href="{{ route('countries.index') }}" class="btn btn-secondary">Go Back</a>
            </div>
        </div>
    </div>
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <!--begin::Form-->
    <form action="{{ route('countries.update',$country->id) }}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <div class="card-body">
            <div class="form-group row">
                <div class="col-lg-4">
                    <label>ID<span class="text-danger">*</span></label>
                    <input type="text" name="id" value="{{ $country->id }}" disabled class="form-control" placeholder="Enter ISO"/>
                    <span class="form-text text-muted">Please enter ISO, Max 2 character allowed</span>
                </div>
                <div class="col-lg-4">
                    <label>Name English<span class="text-danger">*</span></label>
                    <input type="text" name="name" value="{{ $country->name_en }}" required class="form-control" placeholder="Enter Name"/>
                    <span class="form-text text-muted">Please enter Name, Max 50 character allowed</span>
                </div>
                <div class="col-lg-4">
                    <label>Name Arabic<span class="text-danger">*</span></label>
                    <input type="text" name="name_local" value="{{ $country->name_ar }}" class="form-control" placeholder="Enter Local Name"/>
                    <span class="form-text text-muted">Please enter Local Name, Max 50 character allowed</span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-lg-4">
                    <label>Image<span class="text-danger">*</span></label>
                    <div class="image-input image-input-outline" id="kt_image_4" >
                        <div class="image-input-wrapper" style="background-image: url({{$country->flag_url}})"></div>
                        <label class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow" data-action="change" data-toggle="tooltip" title="" data-original-title="Change avatar">
                        <i class="fa fa-pen icon-sm text-muted"></i>
                        <input type="file" name="image" accept=".png, .jpg, .jpeg"/>
                        <input type="hidden" name="profile_avatar_remove"/>
                        </label>

                        <span class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow" data-action="cancel" data-toggle="tooltip" title="Cancel avatar">
                        <i class="ki ki-bold-close icon-xs text-muted"></i>
                        </span>

                        <span class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow" data-action="remove" data-toggle="tooltip" title="Remove avatar">
                        <i class="ki ki-bold-close icon-xs text-muted"></i>
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <div class="row">
                <div class="col-lg-4"></div>
                <div class="col-lg-8">
                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    <button type="reset" class="btn btn-secondary">Cancel</button>
                </div>
            </div>
        </div>
    </form>
    <!--end::Form-->
</div>

@endsection

{{-- Scripts Section --}}
@section('scripts')
<script>
    var avatar4 = new KTImageInput('kt_image_4');

    avatar4.on('cancel', function(imageInput) {
        swal.fire({
            title: 'Image successfully canceled !',
            type: 'success',
            buttonsStyling: false,
            confirmButtonText: 'Awesome!',
            confirmButtonClass: 'btn btn-primary font-weight-bold'
        });
    });

    avatar4.on('change', function(imageInput) {
        swal.fire({
            title: 'Image successfully changed !',
            type: 'success',
            buttonsStyling: false,
            confirmButtonText: 'Awesome!',
            confirmButtonClass: 'btn btn-primary font-weight-bold'
        });
    });

    avatar4.on('remove', function(imageInput) {
        swal.fire({
            title: 'Image successfully removed !',
            type: 'error',
            buttonsStyling: false,
            confirmButtonText: 'Got it!',
            confirmButtonClass: 'btn btn-primary font-weight-bold'
        });
    });
</script>
@endsection